version: "3.8"

services:
  Elasticsearch:
    image: elasticsearch:7.17.8
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  Logstash:
    image: logstash:7.17.8
    container_name: logstash
    restart: always
    # map current folder into container location, not a real volume
    volumes:
      - ./:/logstash_dir
    # fetch config from mapped folder above
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  Kibana:
    image: kibana:7.17.8
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - Elasticsearch

volumes:
  elastic_data:

networks:
  elk:
